[build]
command = "npm run build"
publish = "dist"
functions = "netlify/functions"

[build.environment]
NODE_VERSION = "20"

[[headers]]
for = "/*"
[headers.values]
Cache-Control = "public, max-age=0, must-revalidate"

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200

[[redirects]]
from = "/admin/*"
to = "/admin/index.html"
status = 200

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
